routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'IndexController@index');

Route::get('/list', 'ListController@index');

Auth::routes();

//Custom Routes
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/usersdash', 'AdminController@index')->name('dash');
//User
Route::resource('user', 'UserController');
//Image
Route::resource('image','ImageController')->except(['update']);
Route::patch('/image/{id}/updateActive', 'ImageController@updateActive');
Route::patch('/image/{id}/updatePrimary', 'ImageController@updatePrimary');

//AdminTree
Route::get('/admin/tree/create', 'TreeController@create');
Route::get('/admin/tree', 'AdminController@treeIndex');
Route::get('/admin/tree/{id}/edit', 'TreeController@edit');
Route::post('/tree', 'TreeController@store');
Route::patch('/admin/tree/{id}', 'TreeController@update');
//AdminTrail
Route::get('/admin/trail/create', 'TrailController@create');
Route::get('/admin/trail', 'TrailController@index');
Route::get('/admin/trail/{id}/edit', 'TrailController@edit');
Route::post('/admin/trail', 'TrailController@store');
Route::patch('/admin/trail/{id}', 'TrailController@update');

//Positions
//Tree
Route::get('/admin/tree/{id}/position/create', 'PositionController@createFromTree');
Route::post('/admin/tree/{id}/position', 'PositionController@store');
Route::get('/admin/tree/{tree_id}/position/{position_id}/edit', 'PositionController@editFromTree');
Route::patch('/admin/tree/{id}/position', 'PositionController@update');
//Trail
Route::get('/admin/trail/{id}/position/create', 'PositionController@createFromTrail');
Route::post('/admin/trail/{id}/position', 'PositionController@store');
Route::get('/admin/trail/{id}/position/{position_id}/edit', 'PositionController@editFromTrail');
Route::patch('/admin/trail/{id}/position', 'PositionController@update');


//Tree
Route::get('/tree/upload_csv','TreeController@uploadCsv');
Route::post('/tree/upload_csv','TreeController@loadFromCsv');
Route::get('/tree/get_template', 'TreeController@getTemplateTreesCsv');
Route::get('/tree/{id}', 'TreeController@show');
Route::get('/tree/{id}/add_image', 'TreeController@addImage');
Route::resource('tree', 'TreeController')->only([
    'destroy'
]);
//Route::delete('/tree/{id}', 'TreeController@destroy');
//Trail
Route::get('/trail/{id}', 'TrailController@show');
Route::delete('/trail/{id}', 'TrailController@destroy');
Route::post('/trail/{id}/add_positions', 'TrailController@addPositions');

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Image extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function imageable()
    {
        $this->morphTo();
    }

    public function getPublicFileLocationAttribute()
    {
        return Storage::url($this->file_location);
    }

    public function isPrimary()
    {
        return $this->type === 'primary';
    }
    public function isSecondary()
    {
        return $this->type === 'secondary';
    }

}

app/Tree.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Tree extends Model
{
    protected $table = "trees";

    protected $fillable = [
        'common_name', 'scientific_name', 'description','user_id','active'
    ];

	public function positions(){
        return $this->morphMany(Position::class, 'positionable');
    }

    public function user(){
        return $this->belongsto(User::class, 'user_id');
    }

    public function images() {
        return $this->morphMany(Image::class,'imageable');
    }
}

app/Http/Controllers/TreeController.php
<?php

namespace App\Http\Controllers;

use App\Position;
use App\Tree;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use League\Csv\Writer;
use League\Csv\Reader;

class TreeController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
    }

    public function getTemplateTreesCsv()
    {
        return response()->streamDownload(function () {
            $trees = Tree::all();
            $csv = Writer::createFromFileObject(new \SplTempFileObject());
            $csv->insertOne(['id', 'common_name', 'scientific_name', 'lat', 'lng', 'device']);
            foreach ($trees as $tree) {
                $csv->insertOne([$tree->id, $tree->common_name, $tree->scientific_name, '', '', '']);
            }
            echo $csv;
        }, 'Plantilla_de_Geolocalizaciones.csv');
    }

    public function show($id)
    {
        try {
            $tree = Tree::findOrFail($id);
            $positions = $tree->positions()->get();
            $parent_id = $id;
            $parent_type = 'tree';
            $action = "/admin/tree/$id/position";
            return view('tree.show', [
                'tree' => $tree,
                'positions' => $positions,
                'parent_id' => $parent_id,
                'parent_type' => $parent_type,
                'action' => $action,
            ]);
        } catch (ModelNotFoundException $e) {
            return redirect('/tree')->with('error', 'Arbol no encontrado');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $tree = Tree::findOrFail($id);
            $positions = $tree->positions()->get();
            return view('tree.edit', [
                'tree' => $tree,
                'positions' => $positions,
            ]);
        } catch (ModelNotFoundException $e) {
            return redirect('/admin/tree')->with('error', 'Arbol no encontrado');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tree = Tree::find($id);
        if ($request->has('position')) {
            $oldPosition = $tree->positions()
                ->where('active', true)
                ->first();
            $newPosition = Position::where('id', $request->input('position'))->first();
            if (is_null($oldPosition)) {
                $newPosition->active = true;
                $newPosition->save();
            } elseif ($oldPosition->id !== $newPosition->id) {
                $oldPosition->active = false;
                $oldPosition->save();
                $newPosition->active = true;
                $newPosition->save();
            }
        }
        $tree->common_name = $request->input('common_name');
        $tree->scientific_name = $request->input('scientific_name');
        $tree->description = $request->input('description');
        if ($request->input('active')) {
            $tree->active = true;
        } else {
            $tree->active = false;
        }
        $tree->save();
        return redirect('/admin/tree')->with('success', 'Arbol actualizado');
    }

    /**
     * Show create view for resource.
     *
     * @param  \Illuminate\Http\Request  $request
     */

    public function create()
    {
        return view('tree.create');
    }

    public function loadFromCsv(Request $request)
    {
        $csv = Reader::createFromFileObject($request->file('csv')->openFile());
        $csv->setHeaderOffset(0);
        $records = $csv->getRecords();
        $user = Auth::User();
        foreach ($records as $offset => $record) {
            $tree = Tree::find($record['id']);
            $tree->positions()->create(['lat'=>$record['lat'], 'lng' => $record['lng'], 'user_id' => $user->id, 'active' => false]);
        }
        return redirect('/')-> with(['success'=> 'Carga Exitosa']);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tree = Tree::find($id);
        $positions = $tree->positions()->get();
        foreach ($positions as $position) {
            $position->users()->dissociate();
            $position->delete();
        }
        $tree->user()->dissociate();
        $tree->delete();
        return redirect('/admin/tree')->with('success', 'Árbol eliminado');

    }

    public function uploadCsv() 
    {
        return view('tree.upload_csv');
    }
    public function store(Request $request)
    {
        if (Auth::check() && Auth::User()->isAdmin()) {
            $tree = new Tree();
            $tree->common_name = $request->input('common_name');
            $tree->scientific_name = $request->input('scientific_name');
            $tree->description = $request->input('description');
            if ($request->has('active')) {
                $tree->active = true;
            } else {
                $tree->active = false;
            }
            $tree->user_id = Auth::User()->id;
            $tree->save();
            return redirect("/tree/$tree->id");
        }
        return redirect("/admin/tree")->with('error', 'Usted no es administrador');
    }

    public function addPosition($id)
    {
        $parent_id = Tree::find($id);
        $parent_type = 'tree';
        return view('position.create', [
            'parent_id' => $parent_id,
            'parent_type' => $parent_type,
        ]);
    }

    public function addImage($id): View
    {
        return view('tree.add_image', ['tree' => Tree::findOrFail($id), 'action' => '/image', 'parent_id' => $id, 'parent_type' => 'tree']);
    }
}

resources/views/tree/add_image.blade.php
@extends('layouts.app') 
@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Agregar Imagenes al Arbol - {{$tree->common_name}}</div>

            <div class="card-body">
    @include('components.image.create_form')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tree/create.blade.php
@extends('layouts.app') 
@section('content')
<div class="container">
    <h3>Creación de árbol</h3>
    <form action='/tree' method="POST">
        {{ csrf_field() }}
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="common_name">Nombre común:</label>
                    <input class="form-control" type="text" name="common_name" required>
                </div>
                <div class="form-group">
                    <label for="scientific_name">Nombre científico:</label>
                    <input class="form-control" type="text" name="scientific_name">
                </div>
                <div class="form-group">
                    <label for="active">Activo:</label>
                    <input type="checkbox" name="active" value="true">
                </div>
            </div>
            <div class="form-group col-md-6">
                <label for="description">Descripcción</label>
                <textarea class="form-control" name="description" rows="8" cols="80"></textarea>
            </div>
        </div>
        <input type="submit" class="btn btn-primary" name="crear" value="Crear">
    </form>
</div>
@endsection

resources/views/tree/edit.blade.php
@extends('layouts.app')
@section('content')
<div>
	<section>
		<article>
			<h3>Actualización de datos de árbol</h3>
			<form class="" action="/admin/tree/{{$tree->id}}" method="post">
				{{ csrf_field() }} {{ method_field('PATCH') }}
				<div class="form-row">
					<div class="form-group col-md-4">
						<label for="common_name">Nombre común:</label>
						<input class="form-control" type="text" name="common_name" value="{{$tree->common_name}}">
					</div>
					<div class="form-group col-md-4">
						<label for="scientific_name">Nombre científico:</label>
						<input class="form-control" type="text" name="scientific_name" value="{{$tree->scientific_name}}">
					</div>
					<div class="form-group col-md-4">
						<label for="position">Posición:</label>
						<select name="position" id="position">
								@foreach($positions as $position)
									@if($position->active)
										<option value="{{$position->id}}" selected>{{$position->lat}} ,{{$position->lng}}</option>
									@else
										<option value="{{$position->id}}">{{$position->lat}} ,{{$position->lng}}</option>
									@endif
								@endforeach
							</select>
					</div>
					<div class="form-group col-md-4">
						<label for="description">Descripción:</label>
						<textarea class="form-control" name="description" rows="8" cols="80">{{$tree->description}}</textarea>
					</div>
					<div class="form-group col-md-4">
						<label for="active">Activo:</label> @if($tree->active)
						<input type="checkbox" name="active" value="true" checked> @else
						<input type="checkbox" name="active" value="true"> @endif
					</div>
				</div>
				<input type="submit" class="btn btn-primary" name="update" value="Actualizar">
			</form>
		</article>
	</section>
</div>
@endsection

resources/views/tree/show.blade.php
@extends('layouts.app') 
@section('content')
<div>
    <section>
        <article>
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <h3>Árbol - {{$tree->common_name}} </h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        @if($tree->images()->where('type','primary')->count())
                        <img class="w-100" src="{{$tree->images()->where('type','primary')->first()->public_file_location}}">                        @else
                        <img class="w-100" src="{{asset('/img/simple_tree.svg')}}"> @endif
                    </div>
                    <div class="col-sm-8">
                        <div class="row">
                            <p class="col">
                                <strong>Nombre común:</strong>
                                <span>{{$tree->common_name}}</span>
                            </p>
                            <p class="col">
                                <strong>Nombre Cientifico:</strong>
                                <span>{{$tree->scientific_name}}</span>
                            </p>
                        </div>
                        <div class="row">
                            <div class="col">
                                <strong>Descripción</strong>
                                <p>{{$tree->description}}</p>
                            </div>
                        </div>
                        @guest
                        @else
                        <div class="row control-buttons">
                            <!-- Button trigger modal -->
                            <div class="d-flex justify-content-end w-100 pb-3 pr-3 align-bottom ">
                            <a href="#position_create" class="btn btn-primary mr-2" data-toggle="modal" data-target="#position_create">
                                Agregar Posición
                            </a>
                            <a href="#add_image" class="btn btn-primary mr-2" data-toggle="modal" data-target="#add_image">
                                Agregar Imagen
                            </a>
                            @if($tree->positions()->where('active', true)->count())
                            <a href="#position_map" class="btn btn-primary mr-2" data-toggle="modal" data-target="#position_map">
                                Ver ubicación
                            </a>
                            @endif
                            @if(Auth::User()->isAdmin())
                            <a href="#tree_delete" class="btn btn-danger mr-2" data-toggle="modal" data-target="#tree_delete">
                                Eliminar Árbol
                            </a>
                            @endif
                            </div>

                            <!-- Modal -->
                            <div class="map-modal">
                                <div class="modal fade" id="position_map" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Ubicación</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                                            </div>
                                            <div class="modal-body">
                                                <div id="mapcanvas"></div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal fade" id="add_image" tabindex="-1" role="dialog" aria-labelledby="addImageModal">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="addImageModal">Agregar Imagen</h5>
                                        </div>
                                        <form action="/image" method="post" enctype="multipart/form-data">
                                            <div class="modal-body">
                                                {{ csrf_field() }}
                                                <div class="form-group">
                                                    <label for="image_files">Imagenes:</label>
                                                    <input type="file" name="images[]" id="image_files" class="form-control-file form-control-sm" multiple/>
                                                </div>
                                                <input type="hidden" name="parent_type" value="tree" />
                                                <input type="hidden" name="parent_id" value="{{$tree->id}}" />
                                            </div>
                                            <div class="modal-footer">
                                                <input type="submit" class="btn btn-primary" value="Enviar" />
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="position_create" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Agregar de Posición</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                                </div>
                                <form class="" action="{{$action}}" method="post">
                                    {{ csrf_field() }}
                                    <div class="modal-body">
                                        <div class="form-group col-md-4">
                                            <label for="lat">Latitud:</label>
                                            <input class="form-control" type="text" name="lat" value="">
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="lng">Longitud:</label>
                                            <input class="form-control" type="text" name="lng" value="">
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="device">Dispositivo:</label>
                                            <input class="form-control" type="text" name="device" value="">
                                        </div>
                                        <input type="hidden" name="parent_type" value="{{$parent_type}}" />
                                        <input type="hidden" name="parent_id" value="{{$parent_id}}" />
                                    </div>
                                    <div class="modal-footer">
                                        <input type="submit" class="btn btn-primary" name="create" value="Crear">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    @endguest
                    
                    <!-- Modal -->
                    <div class="modal fade" id="tree_delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminación de árbol</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                                </button>
                                </div>
                                <form class="" action="/tree/{{$tree->id}}" method="post">
                                    {{ csrf_field() }} {{ method_field('DELETE') }}
                                    <div class="modal-body">
                                        <p>Desea eliminar el árbol {{$tree->common_name}}?</p>
                                    </div>
                                    <input type="hidden" name="parent_type" value="tree" />
                                    <input type="hidden" name="parent_id" value="{{$parent_id}}" />
                                    <div class="modal-footer">
                                        <input type="submit" class="btn btn-danger" name="destroy" value="Eliminar">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    @guest
    <br>
    <h3>Imagenes</h3>
    <div class="d-flex flex-wrap">
        @php($cont = 1)
        @foreach($tree->images()->get() as $image)
        <div class="order-{{$cont}} p-2">
            <img src="{{$image->public_file_location}}" style="max-height:150px; max-width:500px" alt="image">
        </div>
        @php($cont++)
        @endforeach
    </div>
    @elseif(Auth::User()->isAdmin())
    @include('components.image.table',['showModifyCol'=> true, 'images' => $tree->images()->get()])
    @else
    <br>
    <h3>Imagenes</h3>
    <div class="d-flex flex-wrap">
        @php($cont = 1) @foreach($tree->images()->get() as $image)
        <div class="order-{{$cont}} p-2">
            <img src="{{$image->public_file_location}}" style="max-height:150px; max-width:500px" alt="image">
        </div>
        @php($cont++) @endforeach
    </div>
    @endguest
        </article>
    </section>
</div>
@endsection
 @if($tree->positions()->where('active',true)->count()) 
@section('script')
<script>
    var map;

google.maps.event.addDomListener(window, 'load', initMap);
function initMap() {
    var position = {!! $tree->positions()->where('active',true)->get(['lat','lng'])->first()->toJson() !!};
    position = {lat:Number(position.lat), lng: Number(position.lng)};
   var mapCanvas = document.getElementById('mapcanvas');
   var mapOptions = {
      center: new google.maps.LatLng(position),
      zoom: 16,
      mapTypeId: google.maps.MapTypeId.ROADMAP
   }

   map = new google.maps.Map(mapCanvas, mapOptions);
   var marker = new google.maps.Marker({
          position: position,
          map: map,
          title: 'Hello World!'
        });
}
    $(document).ready(function(){
        $("#position_map").on('shown.bs.modal', function () {
        google.maps.event.trigger(map, "resize");
    });
});

</script>
@endsection
 @endif 
@section('style')
<style>
    @media (min-width: 576px) {
        div.map-modal .modal-dialog {
            max-width: none;
        }
    }

    div.map-modal .modal-dialog {
        width: 98%;
        height: 92%;
        padding: 0;
    }

    div.map-modal .modal-content {
        height: 99%;
    }

    div.map-modal .modal-body {
        display: -ms-flex;
        display: -webkit-flex;
        display: flex;
    }

    div.map-modal #mapcanvas {
        flex: 1;
    }

    .control-buttons {
        position: absolute;
        bottom: 20px;
        width: 100%;
    }
</style>
@endsection

resources/views/tree/upload_csv.blade.php
@extends('layouts.app') 
@section('content')
<div class="row justify-content-center m-4">
    <div class="col-md-8">
        <h3>Subida de Posiciones de arboles</h3>
        <div class="alert alert-info">
    <p>Para subir geolocalizaciones de forma masiva para los arboles necesitaras utilizar esta plantilla para colocar los posiciones.</p>
    <a class="btn" href="/tree/get_template">Descargar Plantilla</a>
        </div>
    <form action="/tree/upload_csv" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        <lable>Csv:</label>
        <input type="file" class="btn" name="csv" required>
        <input type="submit" class="btn btn-primary" name="submit" value="Enviar">
    </form>
    </div>
</div>
@endsection